version: '3.8'
services:
  limancore:
    build:
      context: https://github.com/hrnrst/dzcore.git#master
      dockerfile: server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - REDIS_HOST=liman-redis
      - REDIS_PASS=liman
      - REDIS_PORT=6379
      - DB_HOST=liman-db
      - DB_DATABASE=liman
      - DB_USERNAME=liman
      - DB_PORT=5432
      - DB_PASS=liman
      - NGINX_PORT=443
    container_name: liman-core
    tty: true
    ports:
      - '443:443'
      - '3000:3000'
    networks:
      - liman-net
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: postgres:15
    container_name: liman-db
    restart: always
    environment:
      - POSTGRES_USER=liman
      - POSTGRES_PASSWORD=liman
      - POSTGRES_DB=liman
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "liman", "-U", "liman"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - liman-net

  redis:
    image: redis
    container_name: liman-redis
    environment:
      - REDIS_PASSWORD=liman
      - REDIS_DISABLE_COMMANDS=CONFIG
    command: >
      --requirepass liman --protected-mode yes
    networks:
      - liman-net

  webssh:
    image: limanmys/webssh:latest
    restart: always
    container_name: liman-webssh
    networks:
      - liman-net

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always
    networks:
      - liman-net

  mysql:
    image: mysql:5.7
    container_name: guac-mysql
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacpass
    volumes:
      - db:/var/lib/mysql
    networks:
      - liman-net

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacpass
    networks:
      - liman-net

volumes:
  db:
    driver: local
  core:
    driver: local
  certs:
    driver: local

networks:
  liman-net:
    name: liman-net
    driver: bridge
