---
- name: Set global version if not provided
  set_fact:
    awx_version: "{{ lookup('file', playbook_dir + '/../VERSION') }}"
  when: awx_version is not defined

- name: Render Dockerfile
  template:
    src: Dockerfile.j2
    dest: ../Dockerfile

# Calling Docker directly because docker-py doesnt support BuildKit
- name: Build AWX image
  command: docker build -t {{ awx_image }}:{{ awx_version }} .

- name: Tag awx images as latest
  command: "docker tag {{ item }}:{{ awx_version }} {{ item }}:latest"
  with_items:
    - "{{ awx_image }}"
